[build]
# Build React app
  command = "cd random-quote-machine && npm install && npm run build && cd ../netlify/functions && npm install"

  # React build output folder
  publish = "random-quote-machine/dist"

[functions]
  # Point Netlify to your functions folder
  directory = "netlify/functions"

[[redirects]]
  # Redirect all /api/* requests to your serverless function
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
